blank_issues_enabled: false
contact_links:
    - name: LIGHTSTAFFLIST SUPPORT
      url: https://www.spigotmc.org/resources/lightstafflist-list-of-all-staff.106172/
      about: Show the players who is guarding your server
