name: Feature request
description: Create a request
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Your requeset
    validations:
      required: true
